baseurl: /SmartdownBlogStarter
port: 4004
ga: true
safe: false
title: BlogKit Example

markdown_ext: 'mkdown,mkdn,mkd'
excerpt_separator: <!--more-->

# plugins_dir         : targets/legacy/_plugins
layouts_dir         : targets/legacy/_layouts
data_dir            : targets/legacy/_data
includes_dir        : targets/legacy/_includes

collections:
  posts:
    output: true
    permalink: /posts/:title/
  rawposts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /pages/:title/
  rawpages:
    output: true
    permalink: /pages/:title

keep_files:
  - assets

include:
  - posts/
  - pages/
  - rawposts/
  - rawpages/
  - targets/legacy/assets/css/*
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # - targets/*
  - targets/legacy/Gemfile*
  - targets/legacy/*.sh
  - targets/cb/
  - targets/mm/
  - hide/

defaults:
  - scope:
      path: "targets/legacy/assets"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default_posts"
  - scope:
      path: "rawposts"
      type: "posts"
    values:
      layout: "raw"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default_pages"
  - scope:
      path: "rawpages"
      type: "pages"
    values:
      layout: "raw"

sass:
  style: compressed
  sass_dir: targets/legacy/_sass
